resources:
  - synopsys_v1_alert.yaml
  - config_map.yaml
  - secret.yaml
  - cfssl_replication_controller.yaml
  - cfssl_service.yaml
  - alert_replication_controller.yaml
  - alert_service.yaml
  # - alert_pvc.yaml

namespace: alt

commonLabels:
  app: alert

vars:
  - name: ALERT_CR_NAME
    objref:
      kind: Alert
      name: changethisalertname
      apiVersion: synopsys.com/v1
    fieldref:
      fieldpath: metadata.name

configurations:
  - kustomizeconfig.yaml

patchesStrategicMerge:
