/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	hubv1 "github.com/blackducksoftware/perceptor-protoform/pkg/api/hub/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHubs implements HubInterface
type FakeHubs struct {
	Fake *FakeSynopsysV1
	ns   string
}

var hubsResource = schema.GroupVersionResource{Group: "synopsys", Version: "v1", Resource: "hubs"}

var hubsKind = schema.GroupVersionKind{Group: "synopsys", Version: "v1", Kind: "Hub"}

// Get takes name of the hub, and returns the corresponding hub object, and an error if there is any.
func (c *FakeHubs) Get(name string, options v1.GetOptions) (result *hubv1.Hub, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hubsResource, c.ns, name), &hubv1.Hub{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hubv1.Hub), err
}

// List takes label and field selectors, and returns the list of Hubs that match those selectors.
func (c *FakeHubs) List(opts v1.ListOptions) (result *hubv1.HubList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hubsResource, hubsKind, c.ns, opts), &hubv1.HubList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hubv1.HubList{ListMeta: obj.(*hubv1.HubList).ListMeta}
	for _, item := range obj.(*hubv1.HubList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hubs.
func (c *FakeHubs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hubsResource, c.ns, opts))

}

// Create takes the representation of a hub and creates it.  Returns the server's representation of the hub, and an error, if there is any.
func (c *FakeHubs) Create(hub *hubv1.Hub) (result *hubv1.Hub, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hubsResource, c.ns, hub), &hubv1.Hub{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hubv1.Hub), err
}

// Update takes the representation of a hub and updates it. Returns the server's representation of the hub, and an error, if there is any.
func (c *FakeHubs) Update(hub *hubv1.Hub) (result *hubv1.Hub, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hubsResource, c.ns, hub), &hubv1.Hub{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hubv1.Hub), err
}

// Delete takes name of the hub and deletes it. Returns an error if one occurs.
func (c *FakeHubs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hubsResource, c.ns, name), &hubv1.Hub{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHubs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hubsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &hubv1.HubList{})
	return err
}

// Patch applies the patch and returns the patched hub.
func (c *FakeHubs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hubv1.Hub, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hubsResource, c.ns, name, pt, data, subresources...), &hubv1.Hub{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hubv1.Hub), err
}
