/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	blackduckv1 "github.com/blackducksoftware/synopsys-operator/pkg/api/blackduck/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBlackducks implements BlackduckInterface
type FakeBlackducks struct {
	Fake *FakeSynopsysV1
	ns   string
}

var blackducksResource = schema.GroupVersionResource{Group: "synopsys", Version: "v1", Resource: "blackducks"}

var blackducksKind = schema.GroupVersionKind{Group: "synopsys", Version: "v1", Kind: "Blackduck"}

// Get takes name of the blackduck, and returns the corresponding blackduck object, and an error if there is any.
func (c *FakeBlackducks) Get(name string, options v1.GetOptions) (result *blackduckv1.Blackduck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(blackducksResource, c.ns, name), &blackduckv1.Blackduck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*blackduckv1.Blackduck), err
}

// List takes label and field selectors, and returns the list of Blackducks that match those selectors.
func (c *FakeBlackducks) List(opts v1.ListOptions) (result *blackduckv1.BlackduckList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(blackducksResource, blackducksKind, c.ns, opts), &blackduckv1.BlackduckList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &blackduckv1.BlackduckList{ListMeta: obj.(*blackduckv1.BlackduckList).ListMeta}
	for _, item := range obj.(*blackduckv1.BlackduckList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested blackducks.
func (c *FakeBlackducks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(blackducksResource, c.ns, opts))

}

// Create takes the representation of a blackduck and creates it.  Returns the server's representation of the blackduck, and an error, if there is any.
func (c *FakeBlackducks) Create(blackduck *blackduckv1.Blackduck) (result *blackduckv1.Blackduck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(blackducksResource, c.ns, blackduck), &blackduckv1.Blackduck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*blackduckv1.Blackduck), err
}

// Update takes the representation of a blackduck and updates it. Returns the server's representation of the blackduck, and an error, if there is any.
func (c *FakeBlackducks) Update(blackduck *blackduckv1.Blackduck) (result *blackduckv1.Blackduck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(blackducksResource, c.ns, blackduck), &blackduckv1.Blackduck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*blackduckv1.Blackduck), err
}

// Delete takes name of the blackduck and deletes it. Returns an error if one occurs.
func (c *FakeBlackducks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(blackducksResource, c.ns, name), &blackduckv1.Blackduck{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBlackducks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(blackducksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &blackduckv1.BlackduckList{})
	return err
}

// Patch applies the patch and returns the patched blackduck.
func (c *FakeBlackducks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *blackduckv1.Blackduck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(blackducksResource, c.ns, name, pt, data, subresources...), &blackduckv1.Blackduck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*blackduckv1.Blackduck), err
}
