---
runtimeobjectsgroupings:
  ServiceAccounts:
    - ServiceAccount.default.eventstore-init
    - ServiceAccount.default.tools-minio-secret-init
    - ServiceAccount.default.upload-server-secret-init
    - ServiceAccount.default.vault-init
  Roles:
    - Role.default.eventstore-init
    - Role.default.tools-minio-secret-init
    - Role.default.upload-server-secret-init
    - Role.default.vault-init
  RoleBindings:
    - RoleBinding.default.eventstore-init
    - RoleBinding.default.tools-minio-secret-init
    - RoleBinding.default.upload-server-secret-init
    - RoleBinding.default.vault-init
  Deployments:
    - Deployment.default.upload-server
    - Deployment.default.mongodb
    - Deployment.default.vault-init
    - Deployment.default.postgresql
    - Deployment.default.swip-db-vault
  StatefulSets:
    - StatefulSet.default.swip-db-consul
    - StatefulSet.default.eventstore
  JobsToRunBefore:
    - Job.default.tools-minio-secret-init
    - Job.default.upload-server-secret-init
    - Job.default.vault-tls-init
  JobsToRunAfter:
    - Job.default.eventstore-init
  Services:
    - Services.default.upload-server
    - Services.default.eventstore
    - Services.default.mongodb
    - Services.default.swip-db-consul
    - Services.default.swip-db-consul-ui
    - Services.default.postgresql
    - Services.default.swip-db-vault
    - Services.default.vault-exporter
  PersistentVolumeClaims:
    - PersistentVolumeClaim.default.postgresql-pv-claim
    - PersistentVolumeClaim.default.upload-server-pv-claim
    - PersistentVolumeClaim.default.mongodb
  Secrets:
    - Secret.default.swip-db-consul-gossip-key
    - Secret.default.smtp
  ConfigMaps:
    - ConfigMap.default.swip-db-consul-tests
    - ConfigMap.default.postgresql-config
    - ConfigMap.default.swip-db-vault-config
    - ConfigMap.default.vault-policies
  PodDisruptionBudgets:
    - PodDisruptionBudget.default.swip-db-consul-pdb
    - PodDisruptionBudget.default.swip-db-vault
runtimeobjectdependencies:
  - obj: RoleBindings
    isdependenton: Roles
  - obj: RoleBindings
    isdependenton: ServiceAccounts
  - obj: Deployments
    isdependenton: RoleBindings
  - obj: Deployments
    isdependenton: PersistentVolumeClaims
  - obj: Deployments
    isdependenton: Secrets
  - obj: Deployments
    isdependenton: ConfigMaps
  - obj: Deployments
    isdependenton: JobsToRunBefore
  - obj: StatefulSets
    isdependenton: RoleBindings
  - obj: StatefulSets
    isdependenton: Secrets
  - obj: StatefulSets
    isdependenton: ConfigMaps
  - obj: StatefulSets
    isdependenton: JobsToRunBefore
  - obj: JobsToRunAfter
    isdependenton: StatefulSets
  - obj: PodDisruptionBudgets
    isdependenton: Deployments
  - obj: Services
    isdependenton: Deployments
    - obj: Services
    isdependenton: StatefulSets
---