---
runtimeobjectsgroupings:
  ConfigMap:
    - ConfigMap.default.demo-alert-blackduck-config
  AlertRC:
    - ReplicationController.default.demo-alert-alert
  CfsslRC:
    - ReplicationController.default.demo-alert-cfssl
  AlertSecret:
    - Secret.default.demo-alert-secret
runtimeobjectdependencies:
#  - obj: AlertRC
#    isdependenton: [ConfigMap, AlertSecret]
  - obj: AlertRC
    isdependenton: AlertSecret
  - obj: CfsslRC
    isdependenton: ConfigMap
  - obj: AlertSecret
    isdependenton: ConfigMap
#  - obj: ConfigMap
#    isdependenton: AlertSecret
---

