apiVersion: synopsys.com/v1
kind: Alert
metadata:
  name: changethisalertname
spec:
  namespace: default
  version: ""
  exposeService: ClusterIP
  standAlone: false
  port: 8443
  EncryptionPassword: "yash"
  EncryptionGlobalSalt: "yash"
  secrets:
    - ENCRYPTION_PASSWORD:<<encryption>>
    - ENCRYPTION_GLOBAL_SALT:<<encryption>>
  environs:
    - ALERT_SERVER_PORT:8443
    - PUBLIC_HUB_WEBSERVER_HOST:<<HOST>>
    - PUBLIC_HUB_WEBSERVER_PORT:443
  persistentStorage: true
  pvcName: alert-pvc
  pvcStorageClass: ""
  pvcSize: 5G
  alertMemory: 2560M
  cfsslMemory: 2560M
  desiredState: START
  imageRegistries: [
    "docker.io/blackducksoftware/blackduck-alert:4.0.0",
    "docker.io/blackduck/blackduck-cfssl:1.0.0"
  ]
  registryConfiguration:
    pullSecrets: [""]
    registry: ""
#  alertImage: docker.io/blackducksoftware/blackduck-alert:4.0.0
