apiVersion: synopsys.com/v1
kind: OpsSight
metadata:
  creationTimestamp: "2019-08-23T16:10:51Z"
  generation: 1
  name: opssight-sample
  resourceVersion: "1342970"
  selfLink: /apis/synopsys.com/v1/opssights/ops
  uid: 937c3800-c5c0-11e9-bb1e-0050568f7601
spec:
  blackduck:
    blackduckPassword: YmxhY2tkdWNr
    blackduckSpec:
      adminPassword: ""
      authCustomCa: ""
      certificateName: default
      desiredState: ""
      exposeService: NONE
      livenessProbes: false
      namespace: ""
      persistentStorage: false
      postgresPassword: ""
      size: Small
      type: pod
      userPassword: ""
      version: ""
    connectionsEnvironmentVariableName: blackduck.json
    deleteBlackduckThresholdPercentage: 50
    externalHosts: null
    initialCount: 0
    maxCount: 0
    tlsVerification: false
  defaultCpu: 300m
  defaultMem: 1300Mi
  desiredState: ""
  enableMetrics: true
  enableSkyfire: false
  isUpstream: false
  logLevel: debug
  namespace: opssight-sample
  perceiver:
    annotationIntervalSeconds: 30
    dumpIntervalMinutes: 30
    enableImagePerceiver: true
    enablePodPerceiver: true
    podPerceiver: {}
  perceptor:
    checkForStalledScansPauseHours: 999999
    clientTimeoutMilliseconds: 100000
    expose: NONE
    modelMetricsPauseSeconds: 15
    stalledScanClientTimeoutHours: 999999
    unknownImagePauseMilliseconds: 15000
  prometheus:
    expose: NONE
  scannerCpu: 300m
  scannerMem: 1300Mi
  scannerPod:
    imageDirectory: "/var/images"
    imageFacade:
      imagePullerType: skopeo
      internalRegistries: []
    scanner:
      clientTimeoutSeconds: 600
    scannerReplicaCount: 1
  skyfire:
    hubClientTimeoutSeconds: 120
    hubDumpPauseSeconds: 240
    kubeDumpIntervalSeconds: 60
    perceptorDumpIntervalSeconds: 60
