/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/blackducksoftware/synopsys-operator/pkg/api/size/v1"
	scheme "github.com/blackducksoftware/synopsys-operator/pkg/size/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SizesGetter has a method to return a SizeInterface.
// A group's client should implement this interface.
type SizesGetter interface {
	Sizes(namespace string) SizeInterface
}

// SizeInterface has methods to work with Size resources.
type SizeInterface interface {
	Create(*v1.Size) (*v1.Size, error)
	Update(*v1.Size) (*v1.Size, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Size, error)
	List(opts metav1.ListOptions) (*v1.SizeList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Size, err error)
	SizeExpansion
}

// sizes implements SizeInterface
type sizes struct {
	client rest.Interface
	ns     string
}

// newSizes returns a Sizes
func newSizes(c *SynopsysV1Client, namespace string) *sizes {
	return &sizes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the size, and returns the corresponding size object, and an error if there is any.
func (c *sizes) Get(name string, options metav1.GetOptions) (result *v1.Size, err error) {
	result = &v1.Size{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sizes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Sizes that match those selectors.
func (c *sizes) List(opts metav1.ListOptions) (result *v1.SizeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SizeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sizes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sizes.
func (c *sizes) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sizes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a size and creates it.  Returns the server's representation of the size, and an error, if there is any.
func (c *sizes) Create(size *v1.Size) (result *v1.Size, err error) {
	result = &v1.Size{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sizes").
		Body(size).
		Do().
		Into(result)
	return
}

// Update takes the representation of a size and updates it. Returns the server's representation of the size, and an error, if there is any.
func (c *sizes) Update(size *v1.Size) (result *v1.Size, err error) {
	result = &v1.Size{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sizes").
		Name(size.Name).
		Body(size).
		Do().
		Into(result)
	return
}

// Delete takes name of the size and deletes it. Returns an error if one occurs.
func (c *sizes) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sizes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sizes) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sizes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched size.
func (c *sizes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Size, err error) {
	result = &v1.Size{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sizes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
