apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: set-file-ownership-blackduck-postgres
  name: set-file-ownership-blackduck-postgres
  namespace: <namespace>
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - chown
            - -R
            - "<security_context>"
            - /setfileownership
          image: docker.io/busybox:1.28
          imagePullPolicy: IfNotPresent
          name: set-file-ownership-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /setfileownership
              name: <name>-blackduck-postgres
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: <name>-blackduck-postgres
          persistentVolumeClaim:
            claimName: <name>-blackduck-postgres

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: set-file-ownership-blackduck-authentication
  name: set-file-ownership-blackduck-authentication
  namespace: <namespace>
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - chown
            - -R
            - "<security_context>"
            - /setfileownership
          image: docker.io/busybox:1.28
          imagePullPolicy: IfNotPresent
          name: set-file-ownership-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /setfileownership
              name: <name>-blackduck-authentication
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: <name>-blackduck-authentication
          persistentVolumeClaim:
            claimName: <name>-blackduck-authentication

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: set-file-ownership-blackduck-cfssl
  name: set-file-ownership-blackduck-cfssl
  namespace: <namespace>
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - chown
            - -R
            - "<security_context>"
            - /setfileownership
          image: docker.io/busybox:1.28
          imagePullPolicy: IfNotPresent
          name: set-file-ownership-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /setfileownership
              name: <name>-blackduck-cfssl
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: <name>-blackduck-cfssl
          persistentVolumeClaim:
            claimName: <name>-blackduck-cfssl

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: set-file-ownership-blackduck-logstash
  name: set-file-ownership-blackduck-logstash
  namespace: <namespace>
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - chown
            - -R
            - "<security_context>"
            - /setfileownership
          image: docker.io/busybox:1.28
          imagePullPolicy: IfNotPresent
          name: set-file-ownership-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /setfileownership
              name: <name>-blackduck-logstash
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: <name>-blackduck-logstash
          persistentVolumeClaim:
            claimName: <name>-blackduck-logstash

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: set-file-ownership-blackduck-registration
  name: set-file-ownership-blackduck-registration
  namespace: <namespace>
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - chown
            - -R
            - "<security_context>"
            - /setfileownership
          image: docker.io/busybox:1.28
          imagePullPolicy: IfNotPresent
          name: set-file-ownership-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /setfileownership
              name: <name>-blackduck-registration
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: <name>-blackduck-registration
          persistentVolumeClaim:
            claimName: <name>-blackduck-registration

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: set-file-ownership-blackduck-uploadcache-data
  name: set-file-ownership-blackduck-uploadcache-data
  namespace: <namespace>
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - chown
            - -R
            - "<security_context>"
            - /setfileownership
          image: docker.io/busybox:1.28
          imagePullPolicy: IfNotPresent
          name: set-file-ownership-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /setfileownership
              name: <name>-blackduck-uploadcache-data
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: <name>-blackduck-uploadcache-data
          persistentVolumeClaim:
            claimName: <name>-blackduck-uploadcache-data

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: set-file-ownership-blackduck-webapp
  name: set-file-ownership-blackduck-webapp
  namespace: <namespace>
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - chown
            - -R
            - "<security_context>"
            - /setfileownership
          image: docker.io/busybox:1.28
          imagePullPolicy: IfNotPresent
          name: set-file-ownership-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /setfileownership
              name: <name>-blackduck-webapp
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: <name>-blackduck-webapp
          persistentVolumeClaim:
            claimName: <name>-blackduck-webapp

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: set-file-ownership-blackduck-zookeeper
  name: set-file-ownership-blackduck-zookeeper
  namespace: <namespace>
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - chown
            - -R
            - "<security_context>"
            - /setfileownership
          image: docker.io/busybox:1.28
          imagePullPolicy: IfNotPresent
          name: set-file-ownership-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /setfileownership
              name: <name>-blackduck-zookeeper
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: <name>-blackduck-zookeeper
          persistentVolumeClaim:
            claimName: <name>-blackduck-zookeeper
