/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/blackducksoftware/synopsys-operator/pkg/api/gr/v1"
	scheme "github.com/blackducksoftware/synopsys-operator/pkg/gr/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GrsGetter has a method to return a GrInterface.
// A group's client should implement this interface.
type GrsGetter interface {
	Grs(namespace string) GrInterface
}

// GrInterface has methods to work with Gr resources.
type GrInterface interface {
	Create(*v1.Gr) (*v1.Gr, error)
	Update(*v1.Gr) (*v1.Gr, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Gr, error)
	List(opts metav1.ListOptions) (*v1.GrList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Gr, err error)
	GrExpansion
}

// grs implements GrInterface
type grs struct {
	client rest.Interface
	ns     string
}

// newGrs returns a Grs
func newGrs(c *SynopsysV1Client, namespace string) *grs {
	return &grs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gr, and returns the corresponding gr object, and an error if there is any.
func (c *grs) Get(name string, options metav1.GetOptions) (result *v1.Gr, err error) {
	result = &v1.Gr{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Grs that match those selectors.
func (c *grs) List(opts metav1.ListOptions) (result *v1.GrList, err error) {
	result = &v1.GrList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested grs.
func (c *grs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("grs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a gr and creates it.  Returns the server's representation of the gr, and an error, if there is any.
func (c *grs) Create(gr *v1.Gr) (result *v1.Gr, err error) {
	result = &v1.Gr{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("grs").
		Body(gr).
		Do().
		Into(result)
	return
}

// Update takes the representation of a gr and updates it. Returns the server's representation of the gr, and an error, if there is any.
func (c *grs) Update(gr *v1.Gr) (result *v1.Gr, err error) {
	result = &v1.Gr{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grs").
		Name(gr.Name).
		Body(gr).
		Do().
		Into(result)
	return
}

// Delete takes name of the gr and deletes it. Returns an error if one occurs.
func (c *grs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *grs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched gr.
func (c *grs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Gr, err error) {
	result = &v1.Gr{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("grs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
