apiVersion: v1
kind: Service
metadata:
  annotations:
    operator.synopsys.com/group-dependencies: "ConfigMap,AlertSecret"
  labels:
    operator.synopsys.com/group-id: "Alert"
    name: $(ALERT_CR_NAME)-alert
  name: $(ALERT_CR_NAME)-alert
spec:
  ports:
    - name: port-8443
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    name: $(ALERT_CR_NAME)-alert
  type: ClusterIP
