apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    operator.synopsys.com/group-dependencies: "ConfigMap"
  labels:
    operator.synopsys.com/group-id: "Cfssl"
    name: $(ALERT_CR_NAME)-cfssl
  name: $(ALERT_CR_NAME)-cfssl
spec:
  replicas: 1
  selector:
    name: $(ALERT_CR_NAME)-cfssl
  template:
    metadata:
      labels:
        name: $(ALERT_CR_NAME)-cfssl
      name: $(ALERT_CR_NAME)-cfssl
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: $(ALERT_CR_NAME)-blackduck-alert-config
          image: docker.io/blackducksoftware/blackduck-cfssl:1.0.0
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - http://localhost:8888/api/v1/cfssl/scaninfo
            failureThreshold: 10
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 10
          name: blackduck-cfssl
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            limits:
              memory: 640M
            requests:
              memory: 640M
          volumeMounts:
            - mountPath: /etc/cfssl
              name: dir-cfssl
      dnsPolicy: ClusterFirst
      volumes:
        - emptyDir: {}
          name: dir-cfssl
