apiVersion: v1
kind: Service
metadata:
  annotations:
    operator.synopsys.com/group-dependencies: "ConfigMap"
  labels:
    operator.synopsys.com/group-id: "Cfssl"
    name: $(ALERT_CR_NAME)-cfssl
  name: $(ALERT_CR_NAME)-cfssl
spec:
  ports:
    - name: port-8888
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    name: $(ALERT_CR_NAME)-cfssl
  type: ClusterIP
