apiVersion: v1
data:
  ALERT_SERVER_PORT: "8443"
  PUBLIC_HUB_WEBSERVER_HOST: localhost
  PUBLIC_HUB_WEBSERVER_PORT: "443"
kind: ConfigMap
metadata:
  annotations:
    operator.synopsys.com/group-dependencies: ""
  labels:
    operator.synopsys.com/group-id: "ConfigMap"
    name: $(ALERT_CR_NAME)-blackduck-alert-config
  name: $(ALERT_CR_NAME)-blackduck-alert-config
