##This configuration is for teaching kustomize how to update name ref and var substitution
# nameReference:
#   - kind: Alert
#     group: synopsys.com
#     fieldSpecs:
#       - kind: Alert
#         group: synopsys.com
#         path: spec/issuerRef/name

# varReference:
#   - kind: Certificate
#     group: certmanager.k8s.io
#     path: spec/commonName
#   - kind: Certificate
#     group: certmanager.k8s.io
#     path: spec/dnsNames
