apiVersion: v1
data:
  ALERT_ENCRYPTION_GLOBAL_SALT: ""
  ALERT_ENCRYPTION_PASSWORD: ""
kind: Secret
metadata:
  annotations:
    # TODO: show what happens if a resource does not have this annotation
    operator.synopsys.com/group-dependencies: "ConfigMap"
  labels:
    # TODO: show what happens if a resource does not have this label
    operator.synopsys.com/group-id: "AlertSecret"
    name: changethisalertname
  name: changethisalertname-alert-secret
type: Opaque
