---
runtimeobjectsgroupings:
  ServiceAccounts:
    - ServiceAccount.auth-server
  Roles:
    - Role.leaderElector
  RoleBindings:
    - RoleBinding.leaderElector
  Deployments:
    - Deployment.auth-server
  HorizontalPodAutoscalers:
    - HorizontalPodAutoscaler.auth-server
  Services:
    - Service.auth-server
runtimeobjectdependencies:
  - obj: RoleBindings
    isdependenton: 
    - Roles
    - ServiceAccounts
  - obj: Deployments
    isdependenton: 
    - RoleBindings
  - obj: HorizontalPodAutoscalers
    isdependenton: 
    - Deployments
---