---
runtimeobjectsgroupings:
  ServiceAccounts:
    - ServiceAccount.eventstore-init
    - ServiceAccount.tools-minio-secret-init
    - ServiceAccount.upload-server-secret-init
    - ServiceAccount.vault-init
  Roles:
    - Role.eventstore-init
    - Role.tools-minio-secret-init
    - Role.upload-server-secret-init
    - Role.vault-init
  RoleBindings:
    - RoleBinding.eventstore-init
    - RoleBinding.tools-minio-secret-init
    - RoleBinding.upload-server-secret-init
    - RoleBinding.vault-init
  Deployments:
    - Deployment.upload-server
    - Deployment.mongodb
    - Deployment.vault-init
    - Deployment.postgresql
    - Deployment.polaris-db-vault
  StatefulSets:
    - StatefulSet.polaris-db-consul
    - StatefulSet.eventstore
  JobsToRunBefore:
    - Job.tools-minio-secret-init
    - Job.upload-server-secret-init
    - Job.vault-tls-init
  JobsToRunAfter:
    - Job.eventstore-init
    - Job.polaris-init-postgres
  Services:
    - Services.upload-server
    - Services.eventstore
    - Services.mongodb
    - Services.polaris-db-consul
    - Services.polaris-db-consul-ui
    - Services.postgresql
    - Services.polaris-db-vault
    - Services.vault-exporter
  PersistentVolumeClaims:
    - PersistentVolumeClaim.postgresql-pv-claim
    - PersistentVolumeClaim.upload-server-pv-claim
    - PersistentVolumeClaim.mongodb
  Secrets:
    - Secret.polaris-db-consul-gossip-key
    - Secret.smtp
  ConfigMaps:
    - ConfigMap.polaris-db-consul-tests
    - ConfigMap.postgresql-config
    - ConfigMap.polaris-db-vault-config
    - ConfigMap.vault-policies
    - ConfigMap.smtp
  PodDisruptionBudgets:
    - PodDisruptionBudget.polaris-db-consul-pdb
    - PodDisruptionBudget.polaris-db-vault
runtimeobjectdependencies:
  - obj: RoleBindings
    isdependenton:
      - Roles
      - ServiceAccounts
  - obj: JobsToRunBefore
    isdependenton:
      - Roles
      - ServiceAccounts
      - RoleBindings
  - obj: Deployments
    isdependenton:
      - RoleBindings
      - PersistentVolumeClaims
      - Secrets
      - ConfigMaps
      - JobsToRunBefore
  - obj: StatefulSets
    isdependenton: 
      - RoleBindings
      - Secrets
      - ConfigMaps
      - JobsToRunBefore
  - obj: JobsToRunAfter
    isdependenton:
      - StatefulSets
      - Deployments
  - obj: PodDisruptionBudgets
    isdependenton:
      - Deployments
---