/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v2

import (
	time "time"

	hubv2 "github.com/blackducksoftware/synopsys-operator/pkg/api/hub/v2"
	versioned "github.com/blackducksoftware/synopsys-operator/pkg/hub/client/clientset/versioned"
	internalinterfaces "github.com/blackducksoftware/synopsys-operator/pkg/hub/client/informers/externalversions/internalinterfaces"
	v2 "github.com/blackducksoftware/synopsys-operator/pkg/hub/client/listers/hub/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HubInformer provides access to a shared informer and lister for
// Hubs.
type HubInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v2.HubLister
}

type hubInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHubInformer constructs a new informer for Hub type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHubInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHubInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHubInformer constructs a new informer for Hub type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHubInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SynopsysV2().Hubs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SynopsysV2().Hubs(namespace).Watch(options)
			},
		},
		&hubv2.Hub{},
		resyncPeriod,
		indexers,
	)
}

func (f *hubInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHubInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hubInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&hubv2.Hub{}, f.defaultInformer)
}

func (f *hubInformer) Lister() v2.HubLister {
	return v2.NewHubLister(f.Informer().GetIndexer())
}
