apiVersion: synopsys.com/v1
kind: OpsSight
metadata:
  clusterName: ""
  name: opssight-test # Required, lowercase letters, numbers, and hyphens only. Cannot start or end with hypens.
spec:
  namespace: opssight-test # Must match .metadata.name

  perceptor:
    name:                           "perceptor"
    port:                           3001
    image:                          "gcr.io/saas-hub-stg/blackducksoftware/perceptor:master"
    checkForStalledScansPauseHours: 999999
    stalledScanClientTimeoutHours:  999999
    modelMetricsPauseSeconds:       15
    unknownImagePauseMilliseconds:  15000
    clientTimeoutMilliseconds:      100000
  
  scannerPod:
    name: "perceptor-scanner"
    scanner:
      name: "perceptor-scanner"
      port:                 3003
      image:                "gcr.io/saas-hub-stg/blackducksoftware/perceptor-scanner:master"
      clientTimeoutSeconds: 600
    imageFacade:
      name: "perceptor-imagefacade"
      port:               3004
      internalRegistries: []
      image:              "gcr.io/saas-hub-stg/blackducksoftware/perceptor-imagefacade:master"
      serviceAccount:     "perceptor-scanner"
    replicaCount: 1
  
  perceiver:
      enableImagePerceiver: false
      enablePodPerceiver:   true
      port:                 3002
      imagePerceiver:
        name:  "image-perceiver"
        image: "gcr.io/saas-hub-stg/blackducksoftware/image-perceiver:master"
      podPerceiver:
        name:  "pod-perceiver"
        image: "gcr.io/saas-hub-stg/blackducksoftware/pod-perceiver:master"
      serviceAccount:            "perceiver"
      annotationIntervalSeconds: 30
      dumpIntervalMinutes:       30

  enableSkyfire: false
  skyfire:
      image:          "gcr.io/saas-hub-stg/blackducksoftware/pyfire:master"
      name:           "skyfire"
      port:           3005
      serviceAccount: "skyfire"
      hubClientTimeoutSeconds: 120
      hubDumpPauseSeconds: 240
      kubeDumpIntervalSeconds: 60
      perceptorDumpIntervalSeconds: 60

  enableMetrics: true
  defaultCPU:    "300m"
  defaultMem:    "1300Mi"
  logLevel:      "debug"
  secretName:    "perceptor"

  hub:
    initialNoOfHubs: 1
    maxNoOfHubs: 4
    concurrentScanLimit: 2
    totalScanLimit: 1000
    hubSpec:
      backupSupport: "No" # Required, possible values are 'Yes', 'No'
      certificateName: default # Required, possible values are 'default', 'manual' or other hub names
      dbPrototype: "empty" # Required, possible values are empty or other hub names
      dockerRegistry: docker.io # Required
      dockerRepo: blackducksoftware # Required
      hubVersion: 5.0.0 # Required
      flavor: small # Required, possible values are 'small', 'medium', 'large' or 'opssight'
      hubType: senthil # Required, possible values are 'master' or 'worker' or 'any custom value to filter the hubs corresponding to particular opssight'
