/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	sizev1 "github.com/blackducksoftware/synopsys-operator/pkg/api/size/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSizes implements SizeInterface
type FakeSizes struct {
	Fake *FakeSynopsysV1
	ns   string
}

var sizesResource = schema.GroupVersionResource{Group: "synopsys", Version: "v1", Resource: "sizes"}

var sizesKind = schema.GroupVersionKind{Group: "synopsys", Version: "v1", Kind: "Size"}

// Get takes name of the size, and returns the corresponding size object, and an error if there is any.
func (c *FakeSizes) Get(name string, options v1.GetOptions) (result *sizev1.Size, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sizesResource, c.ns, name), &sizev1.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sizev1.Size), err
}

// List takes label and field selectors, and returns the list of Sizes that match those selectors.
func (c *FakeSizes) List(opts v1.ListOptions) (result *sizev1.SizeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sizesResource, sizesKind, c.ns, opts), &sizev1.SizeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &sizev1.SizeList{ListMeta: obj.(*sizev1.SizeList).ListMeta}
	for _, item := range obj.(*sizev1.SizeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sizes.
func (c *FakeSizes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sizesResource, c.ns, opts))

}

// Create takes the representation of a size and creates it.  Returns the server's representation of the size, and an error, if there is any.
func (c *FakeSizes) Create(size *sizev1.Size) (result *sizev1.Size, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sizesResource, c.ns, size), &sizev1.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sizev1.Size), err
}

// Update takes the representation of a size and updates it. Returns the server's representation of the size, and an error, if there is any.
func (c *FakeSizes) Update(size *sizev1.Size) (result *sizev1.Size, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sizesResource, c.ns, size), &sizev1.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sizev1.Size), err
}

// Delete takes name of the size and deletes it. Returns an error if one occurs.
func (c *FakeSizes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sizesResource, c.ns, name), &sizev1.Size{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSizes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sizesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &sizev1.SizeList{})
	return err
}

// Patch applies the patch and returns the patched size.
func (c *FakeSizes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *sizev1.Size, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sizesResource, c.ns, name, pt, data, subresources...), &sizev1.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sizev1.Size), err
}
