
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: blackducks.synopsys.com
spec:
  group: synopsys.com
  names:
    kind: Blackduck
    listKind: BlackduckList
    plural: blackducks
    singular: blackduck
  scope: ""
  validation:
    openAPIV3Schema:
      description: Blackduck is the Schema for the blackducks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BlackduckSpec defines the desired state of Blackduck
          properties:
            adminPassword:
              type: string
            authCustomCa:
              type: string
            certificate:
              type: string
            certificateKey:
              type: string
            certificateName:
              type: string
            dbPrototype:
              type: string
            desiredState:
              type: string
            environs:
              items:
                type: string
              type: array
            exposeService:
              type: string
            externalPostgres:
              description: PostgresExternalDBConfig contain the external database
                configuration
              properties:
                postgresAdmin:
                  type: string
                postgresAdminPassword:
                  type: string
                postgresHost:
                  type: string
                postgresPort:
                  type: integer
                postgresSsl:
                  type: boolean
                postgresUser:
                  type: string
                postgresUserPassword:
                  type: string
              required:
              - postgresAdmin
              - postgresAdminPassword
              - postgresHost
              - postgresPort
              - postgresSsl
              - postgresUser
              - postgresUserPassword
              type: object
            imageRegistries:
              items:
                type: string
              type: array
            licenseKey:
              type: string
            livenessProbes:
              type: boolean
            namespace:
              type: string
            persistentStorage:
              type: boolean
            postgresPassword:
              type: string
            proxyCertificate:
              type: string
            pvc:
              items:
                description: PVC will contain the specifications of the different
                  PVC. This will overwrite the default claim configuration
                properties:
                  name:
                    type: string
                  size:
                    type: string
                  storageClass:
                    type: string
                  volumeName:
                    type: string
                required:
                - name
                type: object
              type: array
            pvcStorageClass:
              type: string
            registryConfiguration:
              description: RegistryConfiguration contains the registry configuration
              properties:
                pullSecrets:
                  items:
                    type: string
                  type: array
                registry:
                  type: string
              type: object
            scanType:
              type: string
            size:
              type: string
            type:
              type: string
            userPassword:
              type: string
            version:
              type: string
          required:
          - adminPassword
          - authCustomCa
          - certificateName
          - desiredState
          - exposeService
          - livenessProbes
          - namespace
          - persistentStorage
          - postgresPassword
          - size
          - userPassword
          - version
          type: object
        status:
          description: BlackduckStatus defines the observed state of Blackduck
          properties:
            errorMessage:
              type: string
            fqdn:
              type: string
            ip:
              type: string
            pvcVolumeName:
              additionalProperties:
                type: string
              type: object
            state:
              type: string
          required:
          - ip
          - state
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
