/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	sizev1 "github.com/blackducksoftware/synopsys-operator/pkg/api/size/v1"
	versioned "github.com/blackducksoftware/synopsys-operator/pkg/size/client/clientset/versioned"
	internalinterfaces "github.com/blackducksoftware/synopsys-operator/pkg/size/client/informers/externalversions/internalinterfaces"
	v1 "github.com/blackducksoftware/synopsys-operator/pkg/size/client/listers/size/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SizeInformer provides access to a shared informer and lister for
// Sizes.
type SizeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SizeLister
}

type sizeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSizeInformer constructs a new informer for Size type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSizeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSizeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSizeInformer constructs a new informer for Size type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSizeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SynopsysV1().Sizes(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SynopsysV1().Sizes(namespace).Watch(options)
			},
		},
		&sizev1.Size{},
		resyncPeriod,
		indexers,
	)
}

func (f *sizeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSizeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sizeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sizev1.Size{}, f.defaultInformer)
}

func (f *sizeInformer) Lister() v1.SizeLister {
	return v1.NewSizeLister(f.Informer().GetIndexer())
}
