/*
Copyright (C) 2018 Synopsys, Inc.

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements. See the NOTICE file
distributed with this work for additional information
regarding copyright ownership. The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied. See the License for the
specific language governing permissions and limitations
under the License.
*/

package hub

const (
	GCLOUD_AUTH_FILE_PATH = "/var/secrets/google/key.json"

	// SHARED VALUES
	CFSSL_MEMORY_LIMIT            = "1G"
	LOGSTASH_MEMORY_LIMIT         = "1G"
	REGISTRATION_MEMORY_LIMIT     = "640M"
	ZOOKEEPER_MEMORY_LIMIT        = "384M"
	AUTHENTICATION_MEMORY_LIMIT   = "1024M"
	AUTHENTICATION_HUB_MAX_MEMORY = "512m"
	DOCUMENTATION_MEMORY_LIMIT    = "512M"

	// Ports
	CFSSL_PORT          = "8888"
	WEBSERVER_PORT      = "8443"
	DOCUMENTATION_PORT  = "8443"
	SOLR_PORT           = "8983"
	REGISTRATION_PORT   = "8443"
	ZOOKEEPER_PORT      = "2181"
	JOBRUNNER_PORT      = "3001"
	SCANNER_PORT        = "8443"
	AUTHENTICATION_PORT = "8443"
	WEBAPP_PORT         = "8443"
	LOGSTASH_PORT       = "5044"
	POSTGRES_PORT       = "5432"

	// Small Flavor
	SMALL_WEBSERVER_MEMORY_LIMIT = "640M"
	SMALL_SOLR_MEMORY_LIMIT      = "640M"

	SMALL_WEBAPP_CPU_LIMIT      = "1"
	SMALL_WEBAPP_MEMORY_LIMIT   = "2560M"
	SMALL_WEBAPP_HUB_MAX_MEMORY = "2048m"

	SMALL_SCAN_REPLICAS       = 1
	SMALL_SCAN_MEMORY_LIMIT   = "2560M"
	SMALL_SCAN_HUB_MAX_MEMORY = "2048m"

	SMALL_JOBRUNNER_REPLICAS       = 1
	SMALL_JOBRUNNER_MEMORY_LIMIT   = "4608M"
	SMALL_JOBRUNNER_HUB_MAX_MEMORY = "4096m"

	SMALL_POSTGRES_CPU_LIMIT    = "0.3"
	SMALL_POSTGRES_MEMORY_LIMIT = "300M"

	// Medium Flavor
	MEDIUM_WEBSERVER_MEMORY_LIMIT = "2048M"
	MEDIUM_SOLR_MEMORY_LIMIT      = "1024M"

	MEDIUM_WEBAPP_CPU_LIMIT      = "1"
	MEDIUM_WEBAPP_MEMORY_LIMIT   = "5120M"
	MEDIUM_WEBAPP_HUB_MAX_MEMORY = "4096m"

	MEDIUM_SCAN_REPLICAS       = 2
	MEDIUM_SCAN_MEMORY_LIMIT   = "5120M"
	MEDIUM_SCAN_HUB_MAX_MEMORY = "4096m"

	MEDIUM_JOBRUNNER_REPLICAS       = 4
	MEDIUM_JOBRUNNER_MEMORY_LIMIT   = "7168M"
	MEDIUM_JOBRUNNER_HUB_MAX_MEMORY = "6144m"

	MEDIUM_POSTGRES_CPU_LIMIT    = "2"
	MEDIUM_POSTGRES_MEMORY_LIMIT = "8192M"

	// Large Flavor
	LARGE_WEBSERVER_MEMORY_LIMIT = "2048M"
	LARGE_SOLR_MEMORY_LIMIT      = "1024M"

	LARGE_WEBAPP_CPU_LIMIT      = "1"
	LARGE_WEBAPP_MEMORY_LIMIT   = "9728M"
	LARGE_WEBAPP_HUB_MAX_MEMORY = "8192m"

	LARGE_SCAN_REPLICAS       = 3
	LARGE_SCAN_MEMORY_LIMIT   = "9728M"
	LARGE_SCAN_HUB_MAX_MEMORY = "8192m"

	LARGE_JOBRUNNER_REPLICAS       = 6
	LARGE_JOBRUNNER_MEMORY_LIMIT   = "13824M"
	LARGE_JOBRUNNER_HUB_MAX_MEMORY = "12288m"

	LARGE_POSTGRES_CPU_LIMIT    = "2"
	LARGE_POSTGRES_MEMORY_LIMIT = "12288M"

	// OpsSight Flavor
	OPSSIGHT_WEBSERVER_MEMORY_LIMIT = "2048M"
	OPSSIGHT_SOLR_MEMORY_LIMIT      = "1024M"

	OPSSIGHT_WEBAPP_CPU_LIMIT      = "3"
	OPSSIGHT_WEBAPP_MEMORY_LIMIT   = "19728M"
	OPSSIGHT_WEBAPP_HUB_MAX_MEMORY = "8192m"

	OPSSIGHT_SCAN_REPLICAS       = 5
	OPSSIGHT_SCAN_MEMORY_LIMIT   = "9728M"
	OPSSIGHT_SCAN_HUB_MAX_MEMORY = "8192m"

	OPSSIGHT_JOBRUNNER_REPLICAS       = 10
	OPSSIGHT_JOBRUNNER_MEMORY_LIMIT   = "13824M"
	OPSSIGHT_JOBRUNNER_HUB_MAX_MEMORY = "12288m"

	OPSSIGHT_POSTGRES_CPU_LIMIT    = "3"
	OPSSIGHT_POSTGRES_MEMORY_LIMIT = "12288M"
)
