# Modified from: https://github.com/kubernetes/test-infra/blob/master/prow/cluster/starter.yaml and https://github.com/openshift/release/blob/master/cluster/ci/config/prow/openshift/deck_rbac.yaml

kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      namespace: default
      name: deck
      # annotations:
      #   serviceaccounts.openshift.io/oauth-redirectreference.deck-internal: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"deck-internal"}}'

  - kind: Role
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      namespace: default
      name: deck
    rules:
      - apiGroups:
          - prow.k8s.io
        resources:
          - prowjobs
        verbs:
          - get
          - list

  - kind: Role
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      namespace: test-pods
      name: deck
    rules:
      - apiGroups:
          - ""
        resources:
          - pods/log
        verbs:
          - get

  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      namespace: default
      name: deck
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: deck
    subjects:
      - kind: ServiceAccount
        name: deck

  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      namespace: test-pods
      name: deck
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: deck
    subjects:
      - kind: ServiceAccount
        name: deck
        namespace: default
  # - kind: ClusterRole
  #   apiVersion: rbac.authorization.k8s.io/v1
  #   metadata:
  #     name: deck-oauth
  #   rules:
  #     - apiGroups:
  #         - authentication.k8s.io
  #       resources:
  #         - tokenreviews
  #       verbs:
  #         - create
  #     - apiGroups:
  #         - authorization.k8s.io
  #       resources:
  #         - subjectaccessreviews
  #       verbs:
  #         - create
  # - kind: ClusterRoleBinding
  #   apiVersion: rbac.authorization.k8s.io/v1
  #   metadata:
  #     name: deck-oauth
  #   roleRef:
  #     apiGroup: rbac.authorization.k8s.io
  #     kind: ClusterRole
  #     name: deck-oauth
  #   subjects:
  #     - kind: ServiceAccount
  #       name: deck
  #       namespace: ci
