# Modified from: https://github.com/kubernetes/test-infra/blob/master/prow/cluster/starter.yaml and https://github.com/openshift/release/blob/master/cluster/ci/config/prow/openshift/hook.yaml

kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: default
      name: hook
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "8888"
    spec:
      selector:
        app: prow
        component: hook
      ports:
        - port: 8888
      type: NodePort

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: default
      name: hook
      labels:
        app: prow
        component: hook
    spec:
      replicas: 2
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
      selector:
        matchLabels:
          app: prow
          component: hook
      template:
        metadata:
          labels:
            app: prow
            component: hook
        spec:
          serviceAccountName: hook
          containers:
            - name: hook
              image: gcr.io/k8s-prow/hook:v20190506-dd08c919a
              imagePullPolicy: Always
              args:
                - --dry-run=false
                - --config-path=/etc/config/config.yaml
                - --github-token-path=/etc/github/oauth
                - --hmac-secret-file=/etc/webhook/hmac
                # - --github-endpoint=http://ghproxy
                # - --job-config-path=/etc/job-config
              ports:
                - name: http
                  containerPort: 8888
              volumeMounts:
                - name: hmac
                  mountPath: /etc/webhook
                  readOnly: true
                - name: oauth
                  mountPath: /etc/github
                  readOnly: true
                - name: config
                  mountPath: /etc/config
                  readOnly: true
                - name: plugins
                  mountPath: /etc/plugins
                  readOnly: true
                - name: tmp
                  mountPath: /tmp
                # - name: job-config-misc
                #   mountPath: /etc/job-config/misc
                #   readOnly: true
                # - name: job-config-master
                #   mountPath: /etc/job-config/master
                #   readOnly: true
                # - name: job-config-3x
                #   mountPath: /etc/job-config/3.x
                #   readOnly: true
                # - name: job-config-40
                #   mountPath: /etc/job-config/4.0
                #   readOnly: true
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8081
                initialDelaySeconds: 3
                periodSeconds: 3
              readinessProbe:
                httpGet:
                  path: /healthz/ready
                  port: 8081
                initialDelaySeconds: 10
                periodSeconds: 3
                timeoutSeconds: 600
          volumes:
            - name: hmac
              secret:
                secretName: hmac-token
            - name: oauth
              secret:
                secretName: oauth-token
            - name: config
              configMap:
                name: config
            - name: plugins
              configMap:
                name: plugins
            - name: tmp
              emptyDir: {}
            # - name: job-config-misc
            #   configMap:
            #     name: job-config-misc
            # - name: job-config-master
            #   configMap:
            #     name: job-config-master
            # - name: job-config-3x
            #   configMap:
            #     name: job-config-3.x
            # - name: job-config-40
            #   configMap:
            #     name: job-config-4.0
