# Modified from: https://github.com/kubernetes/test-infra/blob/master/prow/cluster/starter.yaml and https://github.com/openshift/release/blob/master/cluster/ci/config/prow/openshift/horologium_rbac.yaml

kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      namespace: default
      name: horologium

  - kind: Role
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      namespace: default
      name: horologium
    rules:
      - apiGroups:
          - prow.k8s.io
        resources:
          - prowjobs
        verbs:
          - create
          - list

  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      namespace: default
      name: horologium
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: horologium
    subjects:
      - kind: ServiceAccount
        name: horologium
