# Modified from: https://github.com/kubernetes/test-infra/blob/master/prow/cluster/starter.yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: ing
spec:
  rules:
    - http:
        paths:
          - path: /* # Correct for GKE, need / on many other distros
            backend:
              serviceName: deck
              servicePort: 80
          - path: /hook
            backend:
              serviceName: hook
              servicePort: 8888
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-pods
