
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: polarisdbs.synopsys.com
spec:
  group: synopsys.com
  names:
    kind: PolarisDB
    listKind: PolarisDBList
    plural: polarisdbs
    singular: polarisdb
  scope: ""
  validation:
    openAPIV3Schema:
      description: PolarisDB is the Schema for the polarisdbs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PolarisDBSpec defines the desired state of PolarisDB
          properties:
            environment:
              type: string
            environment_address:
              type: string
            eventstore_details:
              properties:
                replicas:
                  format: int32
                  type: integer
                storage_size:
                  type: string
              type: object
            image_pull_secrets:
              type: string
            namespace:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              type: string
            postgres:
              properties:
                host:
                  type: string
                password:
                  type: string
                port:
                  format: int32
                  type: integer
                username:
                  type: string
              required:
              - host
              - password
              - port
              - username
              type: object
            postgres_instance_type:
              type: string
            postgres_storage_details:
              properties:
                size:
                  type: string
                storage_class:
                  type: string
              required:
              - size
              - storage_class
              type: object
            smtp_details:
              properties:
                host:
                  type: string
                password:
                  type: string
                port:
                  format: int32
                  type: integer
                username:
                  type: string
              required:
              - host
              - port
              type: object
            upload_server_details:
              properties:
                replicas:
                  format: int32
                  type: integer
                resources:
                  properties:
                    limits:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                    requests:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                  type: object
                storage:
                  properties:
                    size:
                      type: string
                    storage_class:
                      type: string
                    type:
                      type: string
                  type: object
              type: object
            version:
              type: string
          required:
          - environment
          - environment_address
          - image_pull_secrets
          - postgres
          - postgres_instance_type
          - smtp_details
          - version
          type: object
        status:
          description: PolarisDBStatus defines the observed state of PolarisDB
          properties:
            errorMessage:
              type: string
            state:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
          required:
          - errorMessage
          - state
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
